### ISSUE TITLE
Camera won't open on Android 13 with 12.1.1.GA

### ISSUE THREAD

**Issue by eddyinet** [m1ga/ti.codescanner#1]
Using 1.0.3 released two weeks ago and just upgraded an app to 12.1.1.GA and on Android 13 it brings up the UI with the Scan code interface and colored square scan in the middle but the camera never displays... just black where the image should appear from the camera. Tried manually adding the permissions for Camera just for kicks with same result. Tried downgrading to 1.0.2 with same result. Thoughts?

**Comment by m1ga** [comment]
works fine here. Pixel7 (Android 13) with 1.0.3 with 12.1.1.GA and 12.1.2.GA

SDK shouldn't be involved at all since the module just calls the camera module using the module.

It sounds like your camera is blocked already.

**Comment by eddyinet** [comment]
Hmmm... OK good to know. Happening with all users on Android 13 as well so perhaps permissioning is still required perhaps... not sure what else could be blocking it. Thanks for confirming on your end.... I'll dig into it.

**Comment by m1ga** [comment]
>  as well so perhaps permissioning is still required 

no, that is the whole part of the codescanner, that you don't need permissions.

Check if you have another app in the background that still uses the camera, you should see a dot in the corner for camera activity too. 


I've just searched for "black screen codescanner android" and found this issue:
https://issuetracker.google.com/issues/285007312
and this post with some comments: https://stackoverflow.com/questions/76364252/google-code-scanner-qr-scanner-shows-black-screen-when-launching-it
sounds like it is happening on some phones, so nothing I can do. Sorry

**Comment by eddyinet** [comment]
Thanks so much... no worries... appreciate the feedback. Looks like this is exactly the issues.. .Samsung phones only. Thanks for the link... I'll try and revert to the other scanner module to compensate. Thanks so much!

**Comment by m1ga** [comment]
No problem! it's always Samsung :rofl:
